In [32]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [24]:
#AWS: 방재, ASOS: 종관
#온도 데이터 통합
Years=[2002,2007,2012,2017,2022]
Seasons=['Spring','Summer','Fall','Winter']
temps=[]
for i in Years:
    temps.append(pd.concat([pd.read_excel("C:/Users/bumju/Desktop/공간통계 학술제/raw_data/{}_Temp_ASOS.xlsx".format(i)),
    pd.read_excel("C:/Users/bumju/Desktop/공간통계 학술제/raw_data/{}_Temp_AWS.xlsx".format(i))]))
    

#월->계절 분류
def SeasonLabeling(df):
    data_seasoned=[]
    df['Season']=df['일시'].dt.month
    for i in range(1,13):
        if (i==3)|(i==4)|(i==5):
            df.loc[df['Season']==i,'Season']='Spring'
        elif (i==6)|(i==7)|(i==8):
            df.loc[df['Season']==i,'Season']='Summer'
        elif (i==9)|(i==10)|(i==11):
            df.loc[df['Season']==i,'Season']='Fall'
        elif (i==12)|(i==1)|(i==2):
            df.loc[df['Season']==i,'Season']='Winter'
    spring=df.loc[df['Season']=='Spring'].\
    pivot_table(index=['Point'],columns='Season',values='평균기온(°C)',aggfunc='mean')
    summer=df.loc[df['Season']=='Summer'].\
    pivot_table(index=['Point'],columns='Season',values='평균기온(°C)',aggfunc='mean')
    fall=df.loc[df['Season']=='Fall'].\
    pivot_table(index=['Point'],columns='Season',values='평균기온(°C)',aggfunc='mean')
    winter=df.loc[df['Season']=='Winter'].\
    pivot_table(index=['Point'],columns='Season',values='평균기온(°C)',aggfunc='mean')
    data_seasoned=[spring,summer,fall,winter]
    return data_seasoned
for i in range(0,5):
    temps[i].rename(columns={'지점명':'Point'},inplace=True)
    temps[i]=SeasonLabeling(temps[i])

#index[년도][계절]

In [25]:
df_AWS_obs=pd.read_excel("C:/Users/bumju/Desktop/공간통계 학술제/raw_data/방재기상관측 관측지점 raw data.xlsx",header=1)
df_ASOS_obs=pd.read_excel("C:/Users/bumju/Desktop/공간통계 학술제/raw_data/종관기상관측 관측지점 raw data.xlsx",header=1)
df_total_obs=pd.concat([df_ASOS_obs,df_AWS_obs])
df_total_obs['ST_year']=df_total_obs['시작일'].dt.year
df_total_obs['ST_month']=df_total_obs['시작일'].dt.month
df_total_obs['END_year']=df_total_obs['종료일'].dt.year
df_total_obs['END_month']=df_total_obs['종료일'].dt.month

In [26]:
df_total_obs.rename(columns={'위도':'Lat','경도':'Long','지점명':'Point'},inplace=True)

In [27]:
df_total_obs

,지점,시작일,종료일,Point,지점주소,관리관서,Lat,Long,노장해발고도(m),기압계(관측장비지상높이(m)),기온계(관측장비지상높이(m)),풍속계(관측장비지상높이(m)),강우계(관측장비지상높이(m)),ST_year,ST_month,END_year,END_month
0,90,1968-01-01,NaT,속초,강원특별자치도 고성군토성면 봉포5길9 속초자동기상관측소,속초기상대(90),38.2509,128.5647,17.53,18.73,1.7,10.0,1.4,1968,1,NaN,NaN
1,93,2016-10-01,NaT,북춘천,강원특별자치도 춘천시신북읍 산천리264(장본1길 12) 춘천기상대,춘천기상대(101),37.9474,127.7544,95.78,96.78,1.5,10.0,1.4,2016,10,NaN,NaN
2,95,1988-01-01,NaT,철원,강원특별자치도 철원군갈말읍 명성로179번길 26 철원자동기상관측소,춘천기상대(101),38.1479,127.3042,155.48,156.98,1.8,13.0,1.5,1988,1,NaN,NaN
3,98,1998-02-01,NaT,동두천,경기도 동두천시방죽로 16-47동두천서비스센터,수도권기상청(119),37.9019,127.0607,115.62,116.74,1.7,10.0,1.0,1998,2,NaN,NaN
4,99,2013-10-22,NaT,파주,경기도 파주시문산읍 마정로46-29(파주기상대),수도권기상청(119),37.8859,126.7665,30.59,31.99,1.7,10.0,1.0,2013,10,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2168,989,2021-05-17,NaT,안덕화순,NaN,제주지방기상청(184),33.2579,126.3299,90.00,NaN,NaN,NaN,NaN,2021,5,NaN,NaN
2169,990,2022-10-13,NaT,낙천,NaN,제주지방기상청(184),33.3182,126.2305,77.67,NaN,NaN,NaN,NaN,2022,10,NaN,NaN
2170,990,2021-11-17,2022-10-13,낙천,NaN,제주지방기상청(184),33.3182,126.2305,76.00,NaN,NaN,NaN,NaN,2021,11,2022.0,10.0
2171,991,2021-11-10,NaT,옥포,NaN,대구(구 143),35.8028,128.4456,27.50,NaN,NaN,NaN,NaN,2021,11,NaN,NaN
2172,992,2021-11-10,NaT,하빈,NaN,대구(구 143),35.9062,128.4464,35.50,NaN,NaN,NaN,NaN,2021,11,NaN,NaN

In [28]:
def SeasonDataframe(year, month, df):
    df_season=df.loc[(((df['ST_year']<=year)&((year<df['END_year'])|(df['END_year'].isnull())))|
    ((df['END_year']==year)&(month<=df['END_month'])))].copy()
    return df_season

In [29]:
obs=[]
for i in range(2002,2023,5):
    dfs=[]
    for j in range(5,12,3):
        dfs.append(SeasonDataframe(i,j,df_total_obs))
    dfs.append(SeasonDataframe(i+1,2,df_total_obs))
    obs.append(dfs)

In [30]:
def DfMerge(df1,df2):
    try: df1.set_index('Point',inplace=True)
    except: pass
    df=df1.drop(['지점','시작일', '종료일', '지점주소', '관리관서','노장해발고도(m)',
       '기압계(관측장비지상높이(m))', '기온계(관측장비지상높이(m))', '풍속계(관측장비지상높이(m))',
       '강우계(관측장비지상높이(m))','ST_year','ST_month','END_year','END_month'], axis=1).join(df2,how='inner').copy()
    return df

In [31]:
files=[]

for i in range(0,5):
    for j in range(0,4):
        DfMerge(obs[i][j],temps[i][j]).to_excel("C:/Users/bumju/Desktop/공간통계 학술제/processed_data/Temps_by_Obs_{}_{}.xlsx".format(Years[i],Seasons[j]))

PermissionError: [Errno 13] Permission denied: 'C:/Users/bumju/Desktop/공간통계 학술제/processed_data/Temps_by_Obs_2022_Fall.xlsx'